---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubevirtfolderview-kubevirt-io-github-com-v1alpha1-folderindex
  failurePolicy: Fail
  name: vfolderindex-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kubevirtfolderview.kubevirt.io.github.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - folderindices
  sideEffects: None
