# This rule is not used by the project kubevirt-folder-view itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the kubevirtfolderview.kubevirt.io.github.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-folder-view
    app.kubernetes.io/managed-by: kustomize
  name: folder-editor-role
rules:
- apiGroups:
  - kubevirtfolderview.kubevirt.io.github.com
  resources:
  - folders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubevirtfolderview.kubevirt.io.github.com
  resources:
  - folders/status
  verbs:
  - get
