# This rule is not used by the project kubevirt-folder-view itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kubevirtfolderview.kubevirt.io.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-folder-view
    app.kubernetes.io/managed-by: kustomize
  name: folder-admin-role
rules:
- apiGroups:
  - kubevirtfolderview.kubevirt.io.github.com
  resources:
  - folders
  verbs:
  - '*'
- apiGroups:
  - kubevirtfolderview.kubevirt.io.github.com
  resources:
  - folders/status
  verbs:
  - get
