apiVersion: kubevirtfolderview.kubevirt.io.github.com/v1alpha1
kind: NamespacedFolder
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-folder-view
    app.kubernetes.io/managed-by: kustomize
  name: folder-test
spec:
  virtualMachines:
  - vm1
  - vm2
  childClusterFolders:
  - folder-user
  folderPermissions:
  - subject:
      kind: ServiceAccount
      name: test-user
    roleRefs:
    - apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: admin
