apiVersion: kubevirtfolderview.kubevirt.io.github.com/v1alpha1
kind: ClusterFolder
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-folder-view
    app.kubernetes.io/managed-by: kustomize
  name: folder-admin
spec:
  folderPermissions:
  - subject:
      kind: ServiceAccount
      name: test-admin
    roleRefs:
    - apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: admin
---
apiVersion: kubevirtfolderview.kubevirt.io.github.com/v1alpha1
kind: ClusterFolder
metadata:
  labels:
    app.kubernetes.io/name: kubevirt-folder-view
    app.kubernetes.io/managed-by: kustomize
  name: folder-user
spec:
  folderPermissions:
  - subject:
      kind: ServiceAccount
      name: test-user
    roleRefs:
    - apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: edit
